name: transport_agent
description: Application mobile pour les agents d'embarquement - Transport Interurbain

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # État et navigation
  provider: ^6.1.1
  go_router: ^13.0.0
  
  # Réseau et API
  http: ^1.1.2
  
  # Stockage local
  shared_preferences: ^2.2.2
  
  # QR Code
  mobile_scanner: ^4.0.1
  qr_flutter: ^4.1.0
  
  # UI
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Audio (pour les sons de scan)
  audioplayers: ^5.2.1
  
  # Utilitaires
  intl: ^0.18.1
  
  # Vibration
  vibration: ^1.8.4
  
  # Offline / Synchronisation
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
